import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Inter } from 'next/font/google';

import '@styles/global.css';

import Layout from '@components/Layout';
import ModalsProvider from '@utils/modals/provider';

import type { Metadata } from 'next';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalsProvider>
          <Layout>{children}</Layout>
        </ModalsProvider>
      </body>
    </html>
  );
};

export default RootLayout;
